<?php

namespace Yassine\BackBundle\Repository;
use Yassine\BackBundle\Entity\Avis;

/**
 * avisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisRepository extends \Doctrine\ORM\EntityRepository
{
    public function nbrating($id)
    {
        return $this->createQueryBuilder('g')
            ->select("avg(g.ratingAvis) as rating_avg")
            ->where('g.idOffre = :idOffre')
            ->setParameter('idOffre', $id)
            ->andWhere('g.idClient != :idclient')
            ->setParameter('idclient',14)
            ->getQuery()->getResult();
    }
    public function checkrating($id)
    {

        $em = $this->getDoctrine()->getManager();
        $avis = $em->getRepository('YassineBackBundle:Avis')->findBy(array('idClient'=>$this->getUser()->getId()));

        //$entityManager = $this->getDoctrine()->getManager();
       // $product = $entityManager->getRepository(Avis::class)->find('id_client');

        if (!$avis) {
           return 1;
        }
        $product->setName('New product name!');
        $entityManager->flush();

        return $this->redirectToRoute('product_show', [
            'id' => $product->getId()
        ]);

    }

}
