<?php

namespace Yassine\BackBundle\Repository;

/**
 * experienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperienceRepository extends \Doctrine\ORM\EntityRepository
{
    public function FindExperience($id)
    {
        return $this
            ->createQueryBuilder('a')
            ->select('a')
            ->where('a.idExperience = :idExperience')
            ->setParameter('idExperience', $id)
            ->getQuery()
            ->getResult();
    }
}
