<?php

namespace Yassine\BackBundle\Repository;

/**
 * ListAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListAnswersRepository extends \Doctrine\ORM\EntityRepository
{
    public function FindAnswers($id)
    {
        return $this
            ->createQueryBuilder('a')
            ->select('a')
            ->where('a.idExperience = :idExperience')
            ->setParameter('idExperience', $id)
            ->getQuery()
            ->getResult();
    }
    public function nbrep($id)
    {
        return $this
            ->createQueryBuilder('a')
            ->select('a')
            ->where('a.idClient = :idClient')
            ->setParameter('idClient', $id)
            ->select('COUNT(a.numberPrinted) as fortunesPrinted')
            ->getQuery()
            ->getResult();

        $count = $doctrineEntityManager
            ->getUnitOfWork()
            ->getEntityPersister(Entity::class)
            ->count($criteria);

    }
}
