<?php

namespace Youssef\BackBundle\Repository;

/**
 * SouscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SouscriptionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getstat()
    {
        $rawSql = "SELECT COUNT(Offre) as a,Offre FROM souscription GROUP by Offre";

        $stmt = $this->getEntityManager()->getConnection()->prepare($rawSql);
        $stmt->execute([]);

        return $stmt->fetchAll();


    }
    public function getadminSouscription($id)
    {
        $rawSql = "select * from souscription  where offre in (select id_offre from offre where assureur_id= {$id} )";
        $stmt = $this->getEntityManager()->getConnection()->prepare($rawSql);
        $stmt->execute([]);

        return $stmt->fetchAll();


    }
}
