youssef_front:
    resource: "@YoussefFrontBundle/Resources/config/routing.yml"
    prefix:   /

youssef_back:
    resource: "@YoussefBackBundle/Resources/config/routing.yml"
    prefix:   /
amine:
    resource: "@AmineBundle/Resources/config/routing.yml"
    prefix:   /
yassine_front:
    resource: "@YassineFrontBundle/Resources/config/routing.yml"
    prefix:   /

yassine_back:
    resource: "@YassineBackBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }
farah:
    resource: "@FarahBundle/Resources/config/routing.yml"
    prefix:   /Farah
hayder:
    resource: "@HayderBundle/Resources/config/routing.yml"
    prefix:   /hayder/
toiba_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yaml"
ali_front:
    resource: "@AliFrontBundle/Resources/config/routing.yml"
    prefix:   /
ali_back:
    resource: "@AliBackBundle/Resources/config/routing.yml"
    prefix:   /
