security:
    acl:
        connection: default
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_AGENT:       ROLE_AGENT
        ROLE_CLIENT:      ROLE_CLIENT
        ROLE_EXPERT:      ROLE_EXPERT
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                success_handler: authentication.handler.login_success_handler

            logout:
                path:   fos_user_security_logout
                target: /login
            anonymous:    true

    access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/, role: ROLE_ADMIN }
    - { path: ^/agentaccueil/, role: ROLE_AGENT }
    - { path: ^/useraccueil/, role: ROLE_CLIENT }
    - { path: ^/admin/, role: ROLE_ADMIN }
    - { path: ^/hayder/demande/, role: ROLE_USER }
    - { path: ^/hayder/reclamation/, role: ROLE_USER }
    - { path: ^/hayder/admin/, role: ROLE_ADMIN }