<?php

namespace FarahBundle\Repository;

/**
 * HistoryDonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryDonRepository extends \Doctrine\ORM\EntityRepository
{
}
