<?php

namespace FarahBundle\Repository;

/**
 * ListeDonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeDonRepository extends \Doctrine\ORM\EntityRepository
{
}
