Avis:
    type: entity
    table: avis
    indexes:
        id_offre:
            columns:
                - id_offre
        id_client:
            columns:
                - id_client
    id:
        idAvis:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_avis
            generator:
                strategy: IDENTITY
    fields:
        commentaireAvis:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: commentaire_avis
        dateAvis:
            type: datetime
            nullable: false
            column: date_avis
        ratingAvis:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: rating_avis
    manyToOne:
        idOffre:
            targetEntity: Offre
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_offre:
                    referencedColumnName: id_offre
            orphanRemoval: false
        idClient:
            targetEntity: Client
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_client:
                    referencedColumnName: id_client
            orphanRemoval: false
    lifecycleCallbacks: {  }
