Demande:
    type: entity
    table: demande
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        etat:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        typeDemande:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: type_demande
        motif:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        typeSoin:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: type_soin
        texteLibre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: texte_libre
        pieceJointe:
            type: blob
            nullable: true
            length: null
            options:
                fixed: false
            column: piece_jointe
        reponse:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        gestionnaire:
            type: integer
            nullable: true
            options:
                unsigned: false
        date:
            type: datetime
            nullable: false
        extension:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
