RendezVous:
    type: entity
    table: rendez_vous
    id:
        idRendezVous:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_rendez_vous
            generator:
                strategy: IDENTITY
    fields:
        idExpert:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_expert
        idClient:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_client
        dateRendezVous:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: date_rendez_vous
        lieuRendezVous:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: lieu_rendez_vous
        etat:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
