hayder_demande:
    resource: "@HayderBundle/Resources/config/routing/demande.yml"
    prefix:   /demande

hayder_reclamation:
    resource: "@HayderBundle/Resources/config/routing/reclamation.yml"
    prefix:   /reclamation

stat:
    path:     /stat
    defaults: { _controller: HayderBundle:Default:stat }

pdf:
    path:     /pdf/{reponse}
    defaults: { _controller: HayderBundle:Default:pdf }

recherche_demande:
    path:   /rech/dde
    defaults: { _controller: HayderBundle:Demande:recherche }

recherche_reclamation:
    path:   /rech/rec
    defaults: { _controller: HayderBundle:Reclamation:recherche }

block:
    path:   /block/{id}
    defaults: { _controller: HayderBundle:Default:block }

hayder_back:
    resource: "@HayderBundle/Resources/config/routing/back.yml"
    prefix:   /admin
