<?php

namespace AmineBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RemboursementRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class RemboursementRepository extends EntityRepository
{
}
