<?php

namespace Ali\BackBundle\Repository;

/**
 * rendezVousRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rendezVousRepository extends \Doctrine\ORM\EntityRepository
{
    public function FindRendezVousNonTraitee()
    {
        return $this
            ->createQueryBuilder('a')
            ->select('a')
            ->where('a.etat = :etat')
            ->setParameter('etat', 0)
            ->getQuery()
            ->getResult();
    }
    public function FindRendezVousTerminee()
    {
        return $this
            ->createQueryBuilder('a')
            ->select('a')
            ->where('a.dateRendezVous <= :today')
            ->setParameter('today', new \DateTime())
            ->andWhere('a.etat = :etat')
            ->setParameter('etat', 1)
            ->getQuery()
            ->getResult();
    }
    public function FindMesRendezVous($id)
    {
        return $this
            ->createQueryBuilder('a')
            ->select('a')
            ->where('a.idClient <= :id')
            ->setParameter('id',$id)
            ->getQuery()
            ->getResult();
    }
}
